apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dolphinscheduler-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/zncdatadev/dolphinscheduler-operator-catalog:latest
  displayName: dolphinscheduler catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 5m