apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dolphinscheduler-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: registry.cn-hangzhou.aliyuncs.com/luwei-dev/dolphinscheduler-operator-catalog:latest
  displayName: dolphinscheduler catalog
  publisher: zncdata-labs
  updateStrategy:
    registryPoll:
      interval: 5m